[package]
name = "tracewasm-core"
version = "0.1.0"
edition = "2024"

[dependencies]
wasmparser = { version = "0.253.0" }
thiserror = { workspace = true }
rustc-hash = { workspace = true }
bytemuck = "1.25.2"
tracewasm-macros = { path = "../tracewasm-macros" }
smallvec = { workspace = true }
rustc-demangle = { workspace = true }
addr2line = { workspace = true }
gimli = { workspace = true }
phf = { version = "0.14.0", features = ["macros"] }
id-arena = { workspace = true }
anyhow = { workspace = true }
ordered-float = "5.5.0"

[dev-dependencies]
wat = "1.254.0"
